# frozen_string_literal: true

module SmartBot
  module SkillSystem
    # Execution plan generated by the router
    class ActivationPlan
      attr_reader :skills, :parameters, :primary_skill,
                  :fallback_chain, :parallel_groups, :estimated_cost

      def initialize(skills:, parameters:, primary_skill:,
                     fallback_chain:, parallel_groups:, estimated_cost:)
        @skills = skills
        @parameters = parameters
        @primary_skill = primary_skill
        @fallback_chain = fallback_chain
        @parallel_groups = parallel_groups
        @estimated_cost = estimated_cost
      end

      def empty?
        @skills.empty?
      end

      def single?
        @skills.size == 1
      end

      def parallelizable?
        @parallel_groups.size > 1 ||
          (@parallel_groups.first&.size || 0) > 1
      end

      def to_h
        {
          skills: @skills.map(&:name),
          primary: @primary_skill&.name,
          parameters: @parameters,
          fallback_chain: @fallback_chain.map { |f| f.is_a?(Symbol) ? f : f.name },
          parallel_groups: @parallel_groups.map { |g| g.map(&:name) },
          estimated_cost: @estimated_cost,
          empty: empty?,
          single: single?,
          parallelizable: parallelizable?
        }
      end
    end
  end
end
